### ISSUE TITLE
Switch to using custom uri scheme instead of normal http url

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/clientlib#224]
We will switch to the custom scheme `trustlines://` because using the `http://trustlines.network` would require every app to have access to that domain.

**Comment by dakingha69** [comment]
@berndbohmeier maybe it makes also sense to make this configurable? So adding something like `linkBaseURI` to `TLConfig` which defaults to `trustlines://` but can be customized if wanted. Noticed this while working on issue https://github.com/trustlines-network/mobileapp/issues/452 because we basically have all link creation logic already in the clientlib.

**Comment by berndbohmeier** [comment]
Mmh but I actually would want people to see that this is what the common protocol will be, so I would definilty not want to put it in the config. We could however have it as a optional parameter for the link function.

**Comment by dakingha69** [comment]
Ok makes sense. Optional parameter sounds good then :+1:
